spring:
  profiles:
    active: mariadb
  batch:
    job:
      names: ${job.name:NONE}
---
spring:
  config:
    activate:
      on-profile: mariadb
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/spring_batch
      username: root
      password:
      driver-class-name: org.mariadb.jdbc.Driver