spring:
  profiles:
<<<<<<< HEAD
    active: mariadb
  batch:
    job:
      names: ${job.name:NONE}
---
spring:
  config:
    activate:
      on-profile: mariadb
=======
    active: maria

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: maria
>>>>>>> 6e718b780b14614f150ecfc6417d94b05838154b
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/spring_batch
      username: root
      password:
      driver-class-name: org.mariadb.jdbc.Driver